### ISSUE TITLE
Untrustworthy source for ReVanced patched apps

### ISSUE THREAD

**Issue by Ushie** [anfreire/updateMe-Scrapping#5] opened 2024-08-05 21:29 UTC
Your application uses some releases from revanced.net, [revanced.net is a counterfeit website](https://x.com/revancedapp/status/1764832920882020849) and all the releases there are not trustworthy as anything could be bundled into them

**Comment by anfreire** [comment] 2024-08-10 14:21
Closing this as a duplicate of #7

**Closed by anfreire** 2024-08-10 14:21 UTC
Labels: enhancement
